### PR TITLE
Added and applied ESLint and Prettier

### PR DESCRIPTION
**Pull request by JessicaF**
- Updated configuration for ESLint and Prettier
- Applied both ESLint and Prettier to the frontend folder
- Removed pnpm from frontend because I don't like it and we have npm already

Can both reviewers please check my changes work and haven't messed stuff up - ty!

### CODE REVIEW

**Comment by JessicaF** [comment]
@francojreyes Can we change the CI actions to not use pnpm? Or more broadly, why are we using pnpm in the first place?

**Comment by francojreyes** [comment]
@JessicaF yeah, feel free to remove `pnpm`. We're using it because that's how it's been since 2021 idk lol. I think it feels faster than `npm` personally. If you want me to update CI to use `npm` instead I can, or u can do it urself.

Also, if you're doing things like adding prettier/removing pnpm can you do it for both fe/be? I think it'll be annoying to have to switch between workflows.

**Comment by JessicaF** [comment]
@francojreyes I've configured Prettier and ESLint for the backend as well. Docs are updated on how to use them too. 

Yeah can you update the CI to use npm, or you can tell me where to change that stuff and I'll try?

**Comment by francojreyes** [comment]
@JessicaF I'll try do, I couldn't tell you where to change stuff cos im not rly sure myself lmao

**Pull request merged**
