### PR TITLE
513 - Add filter sidebar for all rooms page

### PR DESCRIPTION
**Pull request by marktran2**
## Overview

To filter all room pages, we will require a filter sidebar to filter room type, location & id required. Refactored the code for a dropdown selection menu for re-usability in codebase.

- also noticed that the filter dropdown had unnecessary padding so removed that too.

## How to view

- add placeholder filter dropdown in any page in local dev environment

## Changes
image
image
image
image

### CODE REVIEW

**Comment by marktran2** [comment]
TODO: add unit tests

**Review by richard-xue-vrx — APPROVED** [review]
Looks good to me! Nice tests, very excited 😳

**Comment by richard-xue-vrx** [comment]
Another thing though; this branch is for the all rooms page, but you can't access the all rooms page at all. Is that intentional?

**Comment by marktran2** [comment]
> Another thing though; this branch is for the all rooms page, but you can't access the all rooms page at all. Is that intentional?

yep this is intentional since the all rooms page is a separate task -> planning to place my changes in once that's in the main branch

**Pull request merged**
