### PR TITLE
feat: update building drawer to be an overlay

### PR DESCRIPTION
**Pull request by SkellyBG**
Update the building drawer modal to be an overlay, instead of pushing everything over

https://www.loom.com/share/84b0daa5745e4a09b07cfb6e1f81297c

### CODE REVIEW

**Comment by richard-xue-vrx** [comment]
Code looks great, but it is a bit annoying having to close the overlay after selecting a room from a building; you can see most of the timetable but its all greyed out in the background. 

Screenshot 2024-07-17 at 4 17 55 pm

**Review by JessicaF — COMMENTED** [review]
Thanks so much for making these changes! Just curious, but is there a way to implement the drawer on the Building page so that there isn't a slight movement when opening and closing it on desktop? 

Also, is it possible to detect a click in the greyed out area to close the drawer - so users don't have to navigate to the close button every time (improves efficiency if don't need to keep closing drawer after opening each building)?

**Comment by SkellyBG** [comment]
I did try having a look at stopping the slight movement but I dug for like half an hour and have no idea why it happens 😔 maybe I'll give it another try tonight. 

Yup, very happy to allow closing the drawer by clicking on the gray area! Thought it should be enabled by default but seems not x.x - if it's a controlled component I can see why it doesn't work - might move the state out of redux store and make it uncontrolled, then it should work in theory.

@JessicaF what do you mean by improves efficiency?

**Comment by JessicaF** [comment]
@SkellyBG I was talking about efficiency as a usability goal (i.e. users don't need to do more mouse movements to close the drawer every time through the button) - too much 3511 😵‍💫

But if the slight movement when opening/closing the drawer is too difficult to achieve then don't worry about it! @richard-xue-vrx  thoughts on needing to fix this movement before getting merged 🤔

**Comment by SkellyBG** [comment]
@JessicaF today is the lucky day xd I fixed the issue ^^
https://www.loom.com/share/d00e5b1ba652433e8075d6ce854d6d11

**Review by JessicaF — APPROVED** [review]
Thanks for the fix! 😄

**Pull request merged**
